"use client";

import { useEffect, useRef, useState } from "react";

type Mode = "solo" | "local" | "online";
type Item = { name:string; icon:string; range:number; damage:number; door?:boolean; heal?:boolean };
type Hero = { id:number; name:string; icon:string; skill:string; color:string; x:number; y:number; hp:number; actions:number; kills:number; xp:number; used:string[]; hands:(Item|null)[]; bag:(Item|null)[] };
type Zombie = { id:number; kind:"walker"|"runner"|"brute"; x:number; y:number; hp:number };
type Game = { heroes:Hero[]; zombies:Zombie[]; active:number; round:number; danger:number; noise:number; mission:string; objectives:string[]; searched:string[]; openDoors:string[]; log:string[]; status:"playing"|"won"|"lost"; mode:Mode };

const W=8,H=6;
const walls = new Set(["2,0","2,1","5,0","5,1","1,3","2,3","5,3","6,3"]);
const buildings = new Set(["0,0","1,0","0,1","1,1","3,0","4,0","3,1","4,1","6,0","7,0","6,1","7,1","0,3","0,4","1,4","2,4","3,3","3,4","4,3","4,4","5,4","6,4","7,3","7,4"]);
const crates = ["0,0","4,1","0,4","4,4","7,4"];
const exits = new Set(["7,2"]);
const makeDoors=(pairs:string[][])=>new Map(pairs.map(([id,room])=>[id.split("|").sort().join("|"),room]));
const doors = makeDoors([["3,2|3,1","3,1"],["4,2|4,1","4,1"],["0,1|0,2","0,1"],["0,2|0,3","0,3"],["3,2|3,3","3,3"],["4,2|4,3","4,3"],["7,2|7,3","7,3"]]);
const spawn = [{x:0,y:2},{x:7,y:5}];
const heroSeeds=[
  ["Maya","⚡","FREE MOVE","#ffc83d"],
  ["Duke","🪓","MELEE +1 DMG","#58d6ff"],
  ["Rook","🎯","RANGED +1 DMG","#fd6c85"],
  ["Doc","✚","FREE SEARCH","#9bea72"],
  ["Nova","↝","SLIPPERY","#f08a38"],
  ["Father Eli","☀","BONUS MELEE","#b43e37"],
  ["Jinx","◆","BONUS RANGED","#a474e8"],
  ["Bear","➶","LONGSHOT","#b98b58"],
] as const;
const ITEMS:Record<string,Item>={Machete:{name:"Machete",icon:"🗡",range:1,damage:1},Shotgun:{name:"Shotgun",icon:"▰",range:2,damage:2},Rifle:{name:"Rifle",icon:"⌁",range:3,damage:1},Pistol:{name:"Pistol",icon:"⌐",range:2,damage:1},"Fire Axe":{name:"Fire Axe",icon:"🪓",range:1,damage:2,door:true},Medkit:{name:"Medkit",icon:"✚",range:0,damage:0,heal:true},Chainsaw:{name:"Chainsaw",icon:"⚙",range:1,damage:2,door:true}};
const loot=Object.keys(ITEMS);
const edge=(a:{x:number,y:number},b:{x:number,y:number})=>[`${a.x},${a.y}`,`${b.x},${b.y}`].sort().join("|");
const itemClass=(name:string)=>`item-${name.toLowerCase().replaceAll(" ","-")}`;
const doorSide=(id:string,room:string)=>{const [rx,ry]=room.split(",").map(Number),other=id.split("|").find(v=>v!==room)!,[ox,oy]=other.split(",").map(Number);return ox<rx?"left":ox>rx?"right":oy<ry?"top":"bottom"};
type Mission={id:string;title:string;story:string;objectivesText:string;min:number;max:number;w:number;h:number;walls:Set<string>;buildings:Set<string>;doors:Map<string,string>;crates:string[];exits:Set<string>;spawn:{x:number,y:number}[];start:{x:number,y:number}};
const MISSIONS:Mission[]=[
 {id:"last-ride",title:"LAST RIDE OUT",story:"An evacuation bus is waiting beyond the barricades. Recover the emergency supplies and get the squad to the extraction lane before the horde closes in.",objectivesText:"Secure 3 supply caches, then evacuate every survivor.",min:2,max:4,w:8,h:6,walls,buildings,doors,crates,exits,spawn,start:{x:3,y:2}},
 {id:"hospital-run",title:"NO QUIET WARD",story:"The Saint Mercy clinic still has antibiotics. Enter through the service corridors, recover two medical crates, and escape through the ambulance bay.",objectivesText:"Recover 2 medical caches and reach the ambulance bay.",min:1,max:3,w:10,h:7,walls:new Set(["2,0","5,0","2,3","5,3","2,5","5,5"]),buildings:new Set(["0,0","1,0","0,1","1,1","3,0","4,0","3,1","4,1","6,0","7,0","6,1","7,1","0,3","1,3","0,4","1,4","3,3","4,3","3,4","4,4","6,3","7,3","6,4","7,4"]),doors:makeDoors([["0,1|0,2","0,1"],["4,1|4,2","4,1"],["7,1|7,2","7,1"],["1,2|1,3","1,3"],["4,2|4,3","4,3"],["6,2|6,3","6,3"],["7,4|7,5","7,4"]]),crates:["0,0","7,4"],exits:new Set(["9,6"]),spawn:[{x:0,y:6},{x:9,y:2}],start:{x:0,y:2}},
 {id:"blackout",title:"BLACKOUT AT PRECINCT 9",story:"The police armory has what the neighborhood needs, but the station is sealed and the streets are dark. Breach carefully—every crash calls more dead.",objectivesText:"Open the armory, secure 4 weapon caches, then hold the north exit.",min:3,max:6,w:12,h:8,walls:new Set(["0,0","1,0","6,0","7,0","2,3","5,3","2,4","5,4","9,2","9,3","9,4"]),buildings:new Set(["2,0","3,0","4,0","5,0","2,1","3,1","4,1","5,1","0,3","1,3","0,4","1,4","3,3","4,3","3,4","4,4","6,3","7,3","6,4","7,4"]),doors:makeDoors([["2,1|2,2","2,1"],["5,1|5,2","5,1"],["1,2|1,3","1,3"],["3,2|3,3","3,3"],["4,2|4,3","4,3"],["6,2|6,3","6,3"]]),crates:["3,0","5,1","0,4","7,4"],exits:new Set(["11,7"]),spawn:[{x:0,y:2},{x:11,y:2},{x:11,y:7}],start:{x:3,y:5}}
];
const canCross=(a:{x:number,y:number},b:{x:number,y:number},open:string[],map:Mission=MISSIONS[0])=>{const key=`${b.x},${b.y}`;if(b.x<0||b.y<0||b.x>=map.w||b.y>=map.h||map.walls.has(key))return false;const boundary=map.buildings.has(`${a.x},${a.y}`)!==map.buildings.has(key);if(!boundary)return true;const e=edge(a,b);return map.doors.has(e)&&open.includes(e)};

function fresh(mode:Mode,mission="last-ride",chosen=[0,1,2,3]):Game{const m=MISSIONS.find(v=>v.id===mission)||MISSIONS[0],hasBreacher=chosen.some(seedIndex=>(["Machete","Shotgun","Rifle","Pistol","Fire Axe","Machete","Pistol","Rifle"][seedIndex]&&ITEMS[["Machete","Shotgun","Rifle","Pistol","Fire Axe","Machete","Pistol","Rifle"][seedIndex]].door)||heroSeeds[seedIndex]?.[2]==="BREACHER"),axeBearer=hasBreacher?-1:Math.floor(Math.random()*chosen.length);
 return {mode,mission,round:1,danger:1,noise:0,active:0,status:"playing",objectives:m.crates.slice(0,mission==="hospital-run"?2:mission==="blackout"?4:3),searched:[],openDoors:[],log:[m.story],
 heroes:chosen.map((seedIndex,partyIndex)=>{const h=heroSeeds[seedIndex];return{id:seedIndex,name:h[0],icon:h[1],skill:h[2],color:h[3],x:m.start.x,y:m.start.y,hp:3,actions:3,kills:0,xp:0,used:[],hands:[ITEMS[["Machete","Shotgun","Rifle","Pistol","Fire Axe","Machete","Pistol","Rifle"][seedIndex]],null],bag:[seedIndex===3?ITEMS.Medkit:null,partyIndex===axeBearer?ITEMS["Fire Axe"]:null,null]}}),
 zombies:[{id:1,kind:"walker",x:m.spawn[0].x,y:m.spawn[0].y,hp:1},{id:2,kind:"walker",x:m.spawn[1]?.x||7,y:m.spawn[1]?.y||5,hp:1},{id:3,kind:"runner",x:m.spawn.at(-1)!.x,y:m.spawn.at(-1)!.y,hp:1}]};
}
const EMPTY_HERO:Hero={id:-1,name:"Fallen Squad",icon:"☠",skill:"LOST",color:"#777",x:0,y:0,hp:0,actions:0,kills:0,xp:0,used:[],hands:[ITEMS.Machete,null],bag:[null,null,null]};

function WebGLEffects({event}:{event:{id:number;kind:string;from?:{x:number,y:number};to?:{x:number,y:number}}|null}){
 const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{if(!event||!ref.current)return;const c=ref.current,gl=c.getContext("webgl",{alpha:true});if(!gl)return;c.width=innerWidth;c.height=innerHeight;const vs=gl.createShader(gl.VERTEX_SHADER)!,fs=gl.createShader(gl.FRAGMENT_SHADER)!;gl.shaderSource(vs,"attribute vec2 p;attribute float s;attribute vec4 c;varying vec4 v;void main(){gl_Position=vec4(p,0.,1.);gl_PointSize=s;v=c;}");gl.shaderSource(fs,"precision mediump float;varying vec4 v;void main(){float d=distance(gl_PointCoord,vec2(.5));if(d>.5)discard;gl_FragColor=vec4(v.rgb,v.a*(1.-d*2.));}");gl.compileShader(vs);gl.compileShader(fs);const pr=gl.createProgram()!;gl.attachShader(pr,vs);gl.attachShader(pr,fs);gl.linkProgram(pr);gl.useProgram(pr);const bp=gl.createBuffer()!,bs=gl.createBuffer()!,bc=gl.createBuffer()!,ap=gl.getAttribLocation(pr,"p"),as=gl.getAttribLocation(pr,"s"),ac=gl.getAttribLocation(pr,"c");const target=event.to||{x:4,y:3},targetCell=document.querySelector<HTMLElement>(`[aria-label="Zone ${target.x+1}, ${target.y+1}"]`),rect=targetCell?.getBoundingClientRect(),px=rect?rect.left+rect.width/2:innerWidth/2,py=rect?rect.top+rect.height/2:innerHeight/2,sx=px/innerWidth*2-1,sy=1-py/innerHeight*2,isDeath=event.kind==="death",count=isDeath?145:event.kind==="shot"?55:90,pts=Array.from({length:count},(_,i)=>({x:sx,y:sy,vx:(Math.random()-.5)*(isDeath?.026:.018),vy:(Math.random()-.5)*.018+(isDeath?.012:0),life:1,size:(isDeath?6:4)+Math.random()*(isDeath?22:18),col:isDeath?(i%3===0?[.48,.015,.01,1]:[.94,.035,.02,1]):i%4===0?[.85,.12,.08,1]:i%3===0?[1,.72,.12,1]:[.28,.34,.22,1]}));let start=performance.now(),raf=0;const draw=(now:number)=>{const dt=Math.min(.035,(now-start)/1000);start=now;gl.clear(gl.COLOR_BUFFER_BIT);const pos:number[]=[],siz:number[]=[],colors:number[]=[];pts.forEach(q=>{q.x+=q.vx;q.y+=q.vy;q.vy-=isDeath?.0012:.0007;q.life-=dt*(isDeath?.95:1.35);pos.push(q.x,q.y);siz.push(q.size*q.life);colors.push(q.col[0],q.col[1],q.col[2],Math.max(0,q.life))});gl.bindBuffer(gl.ARRAY_BUFFER,bp);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(pos),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(ap);gl.vertexAttribPointer(ap,2,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,bs);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(siz),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(as);gl.vertexAttribPointer(as,1,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,bc);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(colors),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(ac);gl.vertexAttribPointer(ac,4,gl.FLOAT,false,0,0);gl.drawArrays(gl.POINTS,0,count);if(pts[0].life>0)raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);gl.deleteProgram(pr)}} , [event]);return <canvas ref={ref} className="fxcanvas" aria-hidden/>;
}

function LandingAtmosphere({active}:{active:boolean}){
 const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{if(!active||!ref.current||matchMedia("(prefers-reduced-motion: reduce)").matches)return;const canvas=ref.current,gl=canvas.getContext("webgl",{alpha:true,antialias:false});if(!gl)return;const resize=()=>{const d=Math.min(devicePixelRatio,1.5);canvas.width=innerWidth*d;canvas.height=innerHeight*d;gl.viewport(0,0,canvas.width,canvas.height)};resize();addEventListener("resize",resize);const vs=gl.createShader(gl.VERTEX_SHADER)!,fs=gl.createShader(gl.FRAGMENT_SHADER)!;gl.shaderSource(vs,"attribute vec2 p;attribute float z;attribute vec4 c;varying vec4 v;void main(){gl_Position=vec4(p,0.,1.);gl_PointSize=z;v=c;}");gl.shaderSource(fs,"precision mediump float;varying vec4 v;void main(){float d=distance(gl_PointCoord,vec2(.5));if(d>.5)discard;float a=smoothstep(.5,.05,d);gl_FragColor=vec4(v.rgb,v.a*a);}");gl.compileShader(vs);gl.compileShader(fs);const program=gl.createProgram()!;gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);gl.useProgram(program);const count=150,particles=Array.from({length:count},(_,i)=>({x:Math.random()*2-1,y:Math.random()*2-1,s:i<115?1+Math.random()*4:3+Math.random()*7,vx:.00015+Math.random()*.00065,vy:(Math.random()-.5)*.00012,ember:i>=115,phase:Math.random()*6.28})),bp=gl.createBuffer()!,bs=gl.createBuffer()!,bc=gl.createBuffer()!,ap=gl.getAttribLocation(program,"p"),az=gl.getAttribLocation(program,"z"),ac=gl.getAttribLocation(program,"c");let raf=0,last=performance.now();const draw=(now:number)=>{const dt=Math.min(32,now-last);last=now;gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);const pos:number[]=[],sizes:number[]=[],colors:number[]=[];for(const q of particles){q.phase+=dt*.002;q.x+=q.vx*dt*(q.ember?.35:1);q.y+=q.vy*dt+(q.ember?.00022*dt:Math.sin(q.phase)*.00004*dt);if(q.x>1.08){q.x=-1.08;q.y=Math.random()*2-1}if(q.ember&&q.y>1.08){q.y=-1.08;q.x=.25+Math.random()*.75}pos.push(q.x,q.y);sizes.push(q.s*(.8+Math.sin(q.phase)*.2));colors.push(...(q.ember?[1,.28,.035,.32+Math.sin(q.phase)*.14]:[.72,.65,.5,.08+Math.sin(q.phase)*.035]))}for(const [b,a,n] of [[bp,ap,2],[bs,az,1],[bc,ac,4]] as const){gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(b===bp?pos:b===bs?sizes:colors),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,n,gl.FLOAT,false,0,0)}gl.drawArrays(gl.POINTS,0,count);raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);removeEventListener("resize",resize);gl.deleteProgram(program)}} ,[active]);return active?<canvas ref={ref} className="landing-atmosphere" aria-hidden/>:null;
}

export default function Home(){
 const [screen,setScreen]=useState<"menu"|"rules"|"game"|"connect"|"setup">("menu");
 const [game,setGame]=useState<Game>(()=>fresh("solo"));
 const [selected,setSelected]=useState<{x:number,y:number}|null>(null);
 const [toast,setToast]=useState("");
 const [sound,setSound]=useState(true); const [music,setMusic]=useState(true);
 const audio=useRef<AudioContext|null>(null),musicAudio=useRef<HTMLAudioElement|null>(null),introTrack=useRef(1+Math.floor(Math.random()*2));
 const [onlineRole,setOnlineRole]=useState<"host"|"guest">("host");
 const [offer,setOffer]=useState(""); const [answer,setAnswer]=useState(""); const [connected,setConnected]=useState(false);
 const [roomId,setRoomId]=useState(""); const [alias,setAlias]=useState(""); const [playerCount,setPlayerCount]=useState(1); const [isHost,setIsHost]=useState(false); const [confirmQuit,setConfirmQuit]=useState(false); const [sessionEnded,setSessionEnded]=useState(false);
 const [chosenMission,setChosenMission]=useState("last-ride"); const [chosenHeroes,setChosenHeroes]=useState<number[]>([0,1]); const [briefing,setBriefing]=useState(false);
 const [setupMode,setSetupMode]=useState<Mode>("solo");
 const [zoom,setZoom]=useState(1);
 const [inventory,setInventory]=useState(false); const [picked,setPicked]=useState<{area:"hands"|"bag";index:number}|null>(null);
 const [selectedDoor,setSelectedDoor]=useState<string|null>(null);
 const [fx,setFx]=useState<{id:number;kind:string;from?:{x:number,y:number};to?:{x:number,y:number}}|null>(null);
 const [alert,setAlert]=useState(""); const [dying,setDying]=useState<Zombie[]>([]);
 const lastRevision=useRef(0),pendingWrites=useRef(0),lastSyncEvent=useRef(""),writeQueue=useRef<Promise<void>>(Promise.resolve());
 const peer=useRef<RTCPeerConnection|null>(null); const channel=useRef<RTCDataChannel|null>(null);
 const rawHero=game.heroes[game.active]||EMPTY_HERO,hero={...rawHero,used:rawHero.used||[]};
 const map=MISSIONS.find(v=>v.id===game.mission)||MISSIONS[0],{walls,buildings,doors,crates,exits,spawn}=map;
 const weapon=hero?.hands.find(Boolean)||ITEMS.Machete;
 const ping=(s:string)=>{setToast(s); setTimeout(()=>setToast(""),1800)};
 const tone=(freq:number,duration=.12,type:OscillatorType="sawtooth",volume=.035)=>{const ctx=audio.current||(audio.current=new AudioContext()),o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(35,freq*.55),ctx.currentTime+duration);g.gain.setValueAtTime(volume,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+duration);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+duration)};
 const toggleSound=()=>{const on=!sound;setSound(on);localStorage.setItem("deadzone-sound",String(on));if(on)tone(90,.12,"triangle",.025)};
 const toggleMusic=()=>{const on=!music;setMusic(on);localStorage.setItem("deadzone-music",String(on));if(!on)musicAudio.current?.pause()};
 const announce=(s:string)=>{setAlert(s);setTimeout(()=>setAlert(""),1500)};
 const send=(g:Game)=>{if(!roomId)return;pendingWrites.current++;writeQueue.current=writeQueue.current.then(async()=>{try{const r=await fetch("/api/rooms",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"update",id:roomId,game:g})}),data=await r.json();if(r.ok&&data.revision)lastRevision.current=Math.max(lastRevision.current,data.revision)}catch{}finally{pendingWrites.current--}})};
 const commit=(fn:(g:Game)=>Game)=>setGame(old=>{const draft=structuredClone(old);draft.heroes.forEach(h=>h.used||=[]);const n=fn(draft);send(n);localStorage.setItem("deadzone-save",JSON.stringify(n));return n});

 useEffect(()=>{ const saved=localStorage.getItem("deadzone-save"); if(saved) try{setGame(JSON.parse(saved))}catch{};const sm=localStorage.getItem("deadzone-music"),ss=localStorage.getItem("deadzone-sound");if(sm!==null)setMusic(sm==="true");if(ss!==null)setSound(ss==="true");const id=new URLSearchParams(location.search).get("room");if(id)joinRoom(id)},[]);
 useEffect(()=>{const a=musicAudio.current;if(!a)return;if(!music){a.pause();return}const gameplay=screen==="game"&&!briefing,target=gameplay?"/music-gameplay.mp3":`/music-intro${introTrack.current}.webm`;if(!a.src.endsWith(target)){a.src=target;a.loop=gameplay;a.volume=gameplay?.38:.28}a.play().catch(()=>{})},[screen,briefing,music]);
 const resumeMusic=()=>{if(music&&musicAudio.current?.paused)musicAudio.current.play().catch(()=>{})};
 const nextIntro=()=>{if(screen==="game"&&!briefing)return;introTrack.current=introTrack.current===1?2:1;const a=musicAudio.current;if(a&&music){a.src=`/music-intro${introTrack.current}.webm`;a.play().catch(()=>{})}};
 useEffect(()=>{if(!roomId)return;const timer=setInterval(async()=>{try{const r=await fetch(`/api/rooms?id=${encodeURIComponent(roomId)}`,{cache:"no-store"}),data=await r.json();if(!r.ok)return;if(data.ended){setSessionEnded(true);setScreen("menu");history.replaceState({},"",location.pathname);setRoomId("");return}setPlayerCount(data.player_count);if(data.game_json&&data.revision>lastRevision.current&&pendingWrites.current===0){const next=JSON.parse(data.game_json);lastRevision.current=data.revision;setGame(old=>{if(next.mission!==old.mission)setBriefing(true);if(next.log?.[0]&&next.log[0]!==old.log?.[0]&&next.log[0]!==lastSyncEvent.current){lastSyncEvent.current=next.log[0];announce(next.log[0].toUpperCase());const focus=next.heroes?.[next.active];if(focus)setFx({id:Date.now(),kind:"sync",to:{x:focus.x,y:focus.y}})}localStorage.setItem("deadzone-save",JSON.stringify(next));return next})}}catch{}},500);return()=>clearInterval(timer)},[roomId]);
 useEffect(()=>{if(screen!=="game")return;requestAnimationFrame(()=>document.querySelector<HTMLElement>("[data-active='true']")?.scrollIntoView({behavior:"smooth",block:"center",inline:"center"}))},[game.active,game.round,screen]);
 useEffect(()=>{const board=document.querySelector<HTMLElement>(".board");if(!board)return;board.style.gridTemplateColumns=`repeat(${map.w},1fr)`;board.style.gridTemplateRows=`repeat(${map.h},1fr)`;board.style.aspectRatio=`${map.w}/${map.h}`;if(map.id==="last-ride"){board.style.width="100%";board.style.height="auto"}else{board.style.width=`${map.w*96*zoom}px`;board.style.height=`${map.h*96*zoom}px`}},[map.id,map.w,map.h,zoom,screen]);
 const start=(mode:Mode)=>{const m=MISSIONS.find(v=>v.id===chosenMission)||MISSIONS[0],valid=chosenHeroes.slice(0,m.max);if(valid.length<m.min)return ping(`Select at least ${m.min} survivors`);const g=fresh(mode,chosenMission,valid);setGame(g);if(roomId)send(g);setBriefing(true);setScreen("game")};
 async function createRoom(){const g=fresh("online");setGame(g);const r=await fetch("/api/rooms",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",game:g})}),data=await r.json();if(!r.ok)return ping("Could not create room");lastRevision.current=data.revision||1;setRoomId(data.id);setAlias("Player 1");setPlayerCount(1);setIsHost(true);setConnected(true);history.replaceState({},"",`?room=${data.id}`);setScreen("connect")}
 async function joinRoom(id:string){try{const j=await fetch("/api/rooms",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"join",id})}),joined=await j.json();if(!j.ok){setSessionEnded(true);return}const r=await fetch(`/api/rooms?id=${encodeURIComponent(id)}`),data=await r.json();lastRevision.current=data.revision||joined.revision||0;setRoomId(id);setAlias(joined.alias);setPlayerCount(joined.playerCount);setIsHost(false);setConnected(true);if(data.game_json)setGame(JSON.parse(data.game_json));setScreen("game")}catch{ping("Could not join this game")}}
 async function terminateGame(){try{if(roomId)await fetch("/api/rooms",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"end",id:roomId})})}finally{setRoomId("");setConnected(false);setConfirmQuit(false);history.replaceState({},"",location.pathname);setScreen("menu")}}
 const log=(g:Game,s:string)=>{g.log=[s,...g.log].slice(0,7)};
 const blocked=(x:number,y:number)=>x<0||y<0||x>=map.w||y>=map.h||walls.has(`${x},${y}`);
 const dist=(a:{x:number,y:number},b:{x:number,y:number})=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
 const lineOfSight=(a:{x:number,y:number},b:{x:number,y:number},range:number)=>{const d=dist(a,b);if(d>=range)return false;if(d===0)return true;if(a.x!==b.x&&a.y!==b.y)return false;const dx=Math.sign(b.x-a.x),dy=Math.sign(b.y-a.y);let cur={x:a.x,y:a.y};while(cur.x!==b.x||cur.y!==b.y){const next={x:cur.x+dx,y:cur.y+dy};if(!canCross(cur,next,game.openDoors,map))return false;cur=next}return true};
 const pathTo=(from:{x:number,y:number},to:{x:number,y:number},open:string[])=>{const queue:[number,number,string[]][]=[[from.x,from.y,[]]],seen=new Set([`${from.x},${from.y}`]);while(queue.length){const [x,y,path]=queue.shift()!;if(x===to.x&&y===to.y)return path;for(const [nx,ny] of [[x+1,y],[x-1,y],[x,y+1],[x,y-1]]){const k=`${nx},${ny}`;if(!seen.has(k)&&canCross({x,y},{x:nx,y:ny},open,map)){seen.add(k);queue.push([nx,ny,[...path,k]])}}}return []};

 function clickCell(x:number,y:number){
  if(game.status!=="playing"||blocked(x,y))return;
  const d=dist(hero,{x,y}); const target=game.zombies.find(z=>z.x===x&&z.y===y);
  const effectiveRange=weapon.range+(hero.skill==="LONGSHOT"&&weapon.range>1?1:0),minimumRange=weapon.name==="Rifle"?1:0;if(target&&d>=minimumRange&&lineOfSight(hero,target,effectiveRange)){attack(target.id);return}
  const door=edge(hero,{x,y});if(d===1&&!canCross(hero,{x,y},game.openDoors,map)){if(doors.has(door)){setSelectedDoor(door);return ping("DOOR SELECTED — use OPEN / BREAK DOOR")}return ping("SOLID WALL — find a door")}
  if(d===1){const trapped=game.zombies.filter(z=>z.x===hero.x&&z.y===hero.y).length,base=1+(hero.skill==="SLIPPERY"?0:trapped),free=hero.skill==="FREE MOVE"&&!hero.used.includes("move"),cost=Math.max(0,base-(free?1:0));if(hero.actions<cost)return ping(trapped?`Need ${cost} AP to escape ${trapped} infected`:"No more APs left to move");commit(g=>{const h=g.heroes[g.active];h.x=x;h.y=y;h.actions-=cost;if(free)h.used.push("move");log(g,`${h.name} moves to ${x+1}-${y+1}${trapped&&!free?` (${cost} AP escape)`:""}.`);return g});return}
  else {setSelected({x,y});ping(target?"NO LINE OF SIGHT / OUT OF RANGE":"Move one zone at a time")}
 }
 function attack(id:number){const z0=game.zombies.find(v=>v.id===id);if(!z0)return;const gun=weapon.range>1,bonusKey=gun?"ranged":"melee",free=(hero.skill==="BONUS RANGED"&&gun||hero.skill==="BONUS MELEE"&&!gun)&&!hero.used.includes(bonusKey);if(hero.actions<1&&!free)return ping("No actions left");if(sound)tone(gun?92:240,gun?.22:.1,gun?"square":"sawtooth",gun?.08:.035);setFx({id:Date.now(),kind:gun?"shot":"slash",from:{x:hero.x,y:hero.y},to:{x:z0.x,y:z0.y}});commit(g=>{const h=g.heroes[g.active], z=g.zombies.find(v=>v.id===id);if(!z)return g;const w=h.hands.find(Boolean)||ITEMS.Machete,damage=w.damage+(h.skill==="MELEE +1 DMG"&&!gun?1:0)+(h.skill==="RANGED +1 DMG"&&gun?1:0);if(free)h.used.push(bonusKey);else h.actions--;z.hp-=damage;if(w.range>1)g.noise+=2;log(g,`${h.name} ${w.range>1?"fires":"swings"} ${w.name} for ${damage}! ${free?"BONUS ATTACK":""}`);if(z.hp<=0){setDying(v=>[...v,{...z}]);setTimeout(()=>setDying(v=>v.filter(q=>q.id!==z.id)),850);setFx({id:Date.now()+1,kind:"death",to:{x:z.x,y:z.y}});g.zombies=g.zombies.filter(v=>v.id!==id);h.kills++;h.xp++;g.danger=1+Math.floor(g.heroes.reduce((n,v)=>n+v.xp,0)/5);log(g,`${z.kind.toUpperCase()} ELIMINATED!`)}return g});announce(gun?"BANG!  BANG!":"SLASH!")}
 function search(){const key=`${hero.x},${hero.y}`,free=hero.skill==="FREE SEARCH"&&!hero.used.includes("search");if((hero.actions<1&&!free)||!buildings.has(key))return ping("Search inside a room");if(game.searched.includes(key))return ping("This room is empty");commit(g=>{const h=g.heroes[g.active];if(free)h.used.push("search");else h.actions--;g.searched.push(key);const name=loot[(g.round+h.id+g.searched.length)%loot.length],item=ITEMS[name],slot=h.bag.findIndex(v=>!v);if(slot<0)log(g,`${name} found — bag full!`);else{h.bag[slot]=item;log(g,`${h.name} stows a ${name}. ${free?"FREE SEARCH":""}`)}if(g.objectives.includes(key)){g.objectives=g.objectives.filter(o=>o!==key);h.xp+=2;log(g,"SUPPLY CACHE SECURED!")}return g});announce("SUPPLIES FOUND")}
 function heal(){const loc=hero.hands.findIndex(v=>v?.heal);if(loc<0||hero.actions<1)return ping("Equip a Medkit in your hand");commit(g=>{const h=g.heroes[g.active];h.actions--;h.hp=Math.min(3,h.hp+2);h.hands[loc]=null;log(g,`${h.name} patches up.`);return g});announce("+2 HEALTH")}
 function healTeammate(targetId:number){const loc=hero.hands.findIndex(v=>v?.heal),target=game.heroes.find(h=>h.id===targetId);if(loc<0)return ping("Equip a Medkit in your hand");if(hero.actions<1)return ping("No actions left to use the Medkit");if(!target||target.x!==hero.x||target.y!==hero.y)return ping("Survivors must share a zone");if(target.hp>=3)return ping(`${target.name} is already at full health`);commit(g=>{const medic=g.heroes[g.active],patient=g.heroes.find(h=>h.id===targetId);if(!patient)return g;medic.actions--;medic.hands[loc]=null;patient.hp=Math.min(3,patient.hp+2);log(g,`${medic.name} uses a Medkit on ${patient.name}.`);return g});announce(`${target.name.toUpperCase()} +2 HEALTH`)}
 function openDoor(){if(hero.actions<1)return;const nearby=[...doors.keys()].filter(k=>k.includes(`${hero.x},${hero.y}`)&&!game.openDoors.includes(k)),adjacent=selectedDoor&&nearby.includes(selectedDoor)?selectedDoor:nearby[0];if(!adjacent)return ping("Stand beside a closed door");const tool=hero.hands.find(v=>v?.door),skill=hero.skill==="BREACHER";if(!tool&&!skill)return ping("Equip an axe, chainsaw, or use Breacher");commit(g=>{g.heroes[g.active].actions--;if(!g.openDoors.includes(adjacent))g.openDoors.push(adjacent);g.noise+=skill?1:3;log(g,`${g.heroes[g.active].name} SMASHES THE DOOR! Noise +${skill?1:3}`);return g});setSelectedDoor(null);setFx({id:Date.now(),kind:"door",to:{x:hero.x,y:hero.y}});announce("CRASH!  HORDE ALERTED")}
 function moveItem(area:"hands"|"bag",index:number){if(!picked){setPicked({area,index});return}if(picked.area===area&&picked.index===index){setPicked(null);return}if(hero.actions<1)return ping("Rearranging costs 1 action");commit(g=>{const h=g.heroes[g.active],a=h[picked.area],b=h[area],[tmp]=[a[picked.index]];a[picked.index]=b[index];b[index]=tmp;h.actions--;log(g,`${h.name} rearranges equipment.`);return g});setPicked(null)}
 function giveItem(index:number,targetId:number){const item=hero.bag[index];if(!item)return;const target=game.heroes.find(h=>h.id===targetId);if(!target||target.x!==hero.x||target.y!==hero.y)return ping("Survivors must share a zone");if(hero.actions<1)return;commit(g=>{const from=g.heroes[g.active],to=g.heroes.find(h=>h.id===targetId);if(!to)return g;const source=from.bag[index],dest=to.bag.findIndex(v=>!v);if(!source)return g;if(dest<0){log(g,`${to.name}'s bag is full.`);return g}from.bag[index]=null;to.bag[dest]={...source};from.actions--;log(g,`${from.name} gives ${source.name} to ${to.name}.`);return g});announce(`${item.name.toUpperCase()} TRANSFERRED`)}
 function yieldTo(index:number){if(index===game.active||game.heroes[index]?.actions<1)return;commit(g=>{g.active=index;log(g,`${g.heroes[index].name} takes initiative.`);return g});announce("INITIATIVE PASSED")}
 function endTurn(){commit(g=>{g.heroes[g.active].actions=0;const next=g.heroes.findIndex(h=>h.actions>0);if(next>=0){g.active=next;log(g,`${g.heroes[next].name}'s turn.`);return g}return zombiePhase(g)});}
 function zombiePhase(g:Game){announce("ZOMBIE PHASE");log(g,"— ZOMBIE PHASE —");for(const z of g.zombies){const alive=g.heroes.filter(h=>h.hp>0);if(!alive.length)break;const routes=alive.map(h=>({h,path:pathTo(z,h,g.openDoors)})).filter(r=>r.path.length||dist(z,r.h)===0).sort((a,b)=>a.path.length-b.path.length),t=routes[0]?.h||alive[0],steps=z.kind==="runner"?2:1;for(let n=0;n<steps;n++){if(dist(z,t)===0){t.hp--;setFx({id:Date.now()+z.id,kind:"bite",to:{x:t.x,y:t.y}});announce(`${t.name.toUpperCase()} HIT!`);log(g,`${t.name} is bitten!`);const possessions=[...t.hands.map((item,index)=>({area:"hands" as const,index,item})),...t.bag.map((item,index)=>({area:"bag" as const,index,item}))].filter(v=>v.item);if(possessions.length&&Math.random()<.3){const lost=possessions[Math.floor(Math.random()*possessions.length)];t[lost.area][lost.index]=null;log(g,`${t.name} loses ${lost.item!.name} in the attack!`);setTimeout(()=>announce(`${t.name.toUpperCase()} LOST ${lost.item!.name.toUpperCase()}!`),650)}break}const route=pathTo(z,t,g.openDoors);if(route.length){const [nx,ny]=route[0].split(",").map(Number);z.x=nx;z.y=ny}else log(g,`${z.kind} claws at a blocked route.`)}}
  let id=Math.max(0,...g.zombies.map(z=>z.id))+1;const fallen=g.heroes.filter(h=>h.hp<=0);for(const h of fallen){g.zombies.push({id:id++,kind:"walker",x:h.x,y:h.y,hp:1});announce(`${h.name.toUpperCase()} HAS TURNED!`);log(g,`${h.name} has turned!`)}g.heroes=g.heroes.filter(h=>h.hp>0);for(const s of spawn){const count=Math.min(3,g.danger);for(let i=0;i<count;i++)g.zombies.push({id:id++,kind:g.round%4===0?"brute":g.round%3===0?"runner":"walker",x:s.x,y:s.y,hp:g.round%4===0?2:1})}
  g.noise=Math.max(0,g.noise-2);g.round++;g.active=0;g.heroes.forEach(h=>{h.actions=3;h.used=[]});if(!g.heroes.length)g.status="lost";else if(!g.objectives.length&&g.heroes.every(h=>exits.has(`${h.x},${h.y}`)))g.status="won";else log(g,`ROUND ${g.round} — ${g.zombies.length} infected roam.`);return g;
 }
 function connectSetup(role:"host"|"guest"){setOnlineRole(role);setOffer("");setAnswer("");setConnected(false);setScreen("connect")}
 const waitIce=(pc:RTCPeerConnection)=>new Promise<void>(res=>{if(pc.iceGatheringState==="complete")res();else pc.onicegatheringstatechange=()=>pc.iceGatheringState==="complete"&&res()});
 function wire(dc:RTCDataChannel){channel.current=dc;dc.onopen=()=>{setConnected(true);ping("Survivors linked!");if(onlineRole==="host")send(game)};dc.onmessage=e=>{try{setGame(JSON.parse(e.data));setScreen("game")}catch{}};dc.onclose=()=>setConnected(false)}
 async function makeOffer(){const pc=new RTCPeerConnection();peer.current=pc;wire(pc.createDataChannel("deadzone"));await pc.setLocalDescription(await pc.createOffer());await waitIce(pc);setOffer(btoa(JSON.stringify(pc.localDescription)));}
 async function acceptOffer(){try{const pc=new RTCPeerConnection();peer.current=pc;pc.ondatachannel=e=>wire(e.channel);await pc.setRemoteDescription(JSON.parse(atob(offer.trim())));await pc.setLocalDescription(await pc.createAnswer());await waitIce(pc);setAnswer(btoa(JSON.stringify(pc.localDescription)))}catch{ping("That invite code is invalid")}}
 async function acceptAnswer(){try{await peer.current?.setRemoteDescription(JSON.parse(atob(answer.trim())))}catch{ping("That answer code is invalid")}}

 const canEvac=!game.objectives.length,heroKey=`${hero.x},${hero.y}`,freeSearch=hero.skill==="FREE SEARCH"&&!hero.used.includes("search"),canSearch=(hero.actions>0||freeSearch)&&buildings.has(heroKey)&&!game.searched.includes(heroKey),searchTip=!buildings.has(heroKey)?"Move into a room to search":game.searched.includes(heroKey)?"This room has already been searched":"No actions left to search",closedDoor=[...doors.keys()].some(id=>id.split("|").includes(heroKey)&&!game.openDoors.includes(id)),hasBreach=hero.skill==="BREACHER"||hero.hands.some(v=>v?.door),canOpenDoor=hero.actions>0&&closedDoor&&hasBreach,doorTip=!closedDoor?"Stand beside a closed door":!hasBreach?"Equip a Fire Axe or another breaching tool":"No actions left to open the door",hasMedkit=hero.hands.some(v=>v?.heal),canHeal=hero.actions>0&&hasMedkit,healTip=!hasMedkit?"Equip a Medkit in your hand":"No actions left to use the Medkit";
 return <main className="shell" onPointerDown={resumeMusic}>
  <audio ref={musicAudio} preload="auto" onEnded={nextIntro}/>
  <LandingAtmosphere active={screen==="menu"||(screen==="game"&&game.status!=="playing")}/>
  <div className="global-audio"><button onClick={toggleMusic} aria-label={music?"Turn music off":"Turn music on"} data-tooltip={music?"Turn music off":"Turn music on"}>{music?"♫":"♫̸"}</button><button onClick={toggleSound} aria-label={sound?"Turn sound effects off":"Turn sound effects on"} data-tooltip={sound?"Turn sound effects off":"Turn sound effects on"}>{sound?"◉":"○"}</button></div>
  <WebGLEffects event={fx}/>{alert&&<div className="action-alert"><span>{alert}</span></div>}
  {toast&&<div className="toast">{toast}</div>}
  {screen==="game"&&<div className="initiative-dock"><small>PASS INITIATIVE</small>{game.heroes.map((h,i)=><button key={h.id} disabled={i===game.active||h.actions<1} onClick={()=>yieldTo(i)} className={i===game.active?"active":""}>{h.name}<b>{h.actions} AP</b></button>)}</div>}
  {screen==="game"&&map.id!=="last-ride"&&<div className="zoom-controls"><button onClick={()=>setZoom(v=>Math.max(.65,v-.15))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(v=>Math.min(1.5,v+.15))}>+</button></div>}
  {screen==="menu"&&<section className="menu">
   <div className="blood">THE CITY IS LOST</div><h1>DEAD ZONE<br/><em>LAST STAND</em></h1><p className="tag">A COOPERATIVE SURVIVAL BOARD GAME</p>
   <div className="mode-grid">
    <button onClick={()=>{setSetupMode("solo");setScreen("setup")}}><b>SOLO CAMPAIGN</b><span>Choose a mission and squad</span></button>
    <button onClick={()=>{setSetupMode("local");setScreen("setup")}}><b>COUCH CO-OP</b><span>Choose a mission and squad</span></button>
    <button onClick={createRoom}><b>ONLINE CO-OP</b><span>Create one link. Friends join instantly.</span></button>
   </div>
   <div className="menu-row"><button className="textbtn" onClick={()=>setScreen("rules")}>HOW TO PLAY</button><button className="textbtn" onClick={()=>{const s=localStorage.getItem("deadzone-save");if(s){setGame(JSON.parse(s));setScreen("game")}}}>CONTINUE</button></div>
   <div className="background-fires" aria-hidden><i/><i/><i/></div><div className="zombie-silhouette">🧟</div><small className="build-version">BUILD 20260711-16</small>{sessionEnded&&<div className="sessionnotice"><b>THE HOST ENDED THE GAME</b><button onClick={()=>setSessionEnded(false)}>DISMISS</button></div>}
  </section>}
  {screen==="setup"&&<section className="setup-screen"><button className="back" onClick={()=>setScreen(setupMode==="online"?"connect":"menu")}>← BACK</button><div className="setup-head"><span>MISSION CONTROL</span><h2>CHOOSE YOUR LAST STAND</h2><p>The host chooses the scenario and survivor roster. Every mission has its own map, squad limits, story, and objectives.</p></div><div className="mission-cards">{MISSIONS.map(m=><button key={m.id} className={chosenMission===m.id?"selected":""} onClick={()=>{setChosenMission(m.id);setChosenHeroes(v=>v.slice(0,m.max))}}><small>MISSION {MISSIONS.indexOf(m)+1}</small><b>{m.title}</b><p>{m.story}</p><i>{m.objectivesText}</i><span>SQUAD {m.min}–{m.max}</span></button>)}</div><div className="roster-head"><h3>SELECT SURVIVORS</h3><span>{chosenHeroes.length} / {(MISSIONS.find(m=>m.id===chosenMission)||MISSIONS[0]).max}</span></div><div className="roster-grid">{heroSeeds.map((h,i)=><button key={h[0]} className={`${chosenHeroes.includes(i)?"selected":""} recruit recruit-${i}`} onClick={()=>{const m=MISSIONS.find(v=>v.id===chosenMission)||MISSIONS[0];setChosenHeroes(v=>v.includes(i)?v.filter(x=>x!==i):v.length<m.max?[...v,i]:v)}}><span className="recruit-portrait"/><i>{h[1]}</i><b>{h[0]}</b><small>{h[2]}</small></button>)}</div><button className="primary launch" onClick={()=>start(setupMode)}>LAUNCH MISSION →</button></section>}
  {screen==="rules"&&<section className="paper"><button className="back" onClick={()=>setScreen("menu")}>← BACK</button><h2>FIELD MANUAL</h2><div className="rules-grid"><article><b>1. SURVIVORS</b><p>Each survivor gets 3 actions: move, attack, search, heal, or pass.</p></article><article><b>2. THE HORDE</b><p>After the whole team acts, zombies move, bite, and new infected spawn.</p></article><article><b>3. THE MISSION</b><p>Search all three red supply caches, then move every survivor onto the green evac zone.</p></article><article><b>4. COMBAT</b><p>Click an infected in weapon range. Brutes take 2 damage. Danger and spawns rise with XP.</p></article></div><button className="primary" onClick={()=>start("solo")}>BEGIN MISSION</button></section>}
  {screen==="connect"&&<section className="paper connect"><button className="back" onClick={terminateGame}>← CANCEL ROOM</button><h2>YOUR GAME IS READY</h2><p>You are <b>{alias}</b>. Send this link to your friends—they will be assigned Player 2, Player 3, and so on automatically.</p><a className="invite-link" href={`${typeof location!=="undefined"?location.origin:""}?room=${roomId}`} onClick={e=>{e.preventDefault();navigator.clipboard.writeText((e.currentTarget as HTMLAnchorElement).href);ping("Invite link copied!")}}>{typeof location!=="undefined"?`${location.origin}?room=${roomId}`:`ROOM ${roomId}`}</a><div className="lobbycount"><b>{playerCount}</b><span>PLAYER{playerCount===1?"":"S"} IN SESSION</span></div><button className="primary" onClick={()=>{setSetupMode("online");setScreen("setup")}}>SELECT MISSION & SQUAD</button>
  </section>}
  {screen==="game"&&<section className="game">
   <header><button className="logo" onClick={()=>roomId?(isHost?setConfirmQuit(true):terminateGame()):setScreen("menu")}>DEAD ZONE</button><div className="mission"><span>MISSION {MISSIONS.findIndex(m=>m.id===map.id)+1}</span><b>{map.title}</b></div>{roomId&&<div className="players"><b>{alias}</b><span>{playerCount} ONLINE</span></div>}<div className="round">ROUND <b>{game.round}</b></div><div className="noise">NOISE <b>{"!".repeat(Math.min(5,game.noise))||"—"}</b></div><div className={`danger d${Math.min(game.danger,4)}`}>DANGER <b>{["","LOW","RISING","HIGH","RED"][Math.min(game.danger,4)]}</b></div><button className="quitbtn" onClick={()=>roomId&&isHost?setConfirmQuit(true):roomId?terminateGame():setScreen("menu")}>☰ EXIT</button><button className="iconbtn" onClick={()=>setScreen("rules")}>?</button></header>
   <div className="gamebody"><aside className="squad"><h3>SURVIVORS</h3>{game.heroes.map((h,i)=><button key={h.id} className={`hero ${i===game.active?"active":""}`} onClick={()=>game.mode==="solo"&&i===game.active&&setSelected({x:h.x,y:h.y})} style={{"--c":h.color} as React.CSSProperties}><span className={`portrait portrait-${h.id}`}><i className="skilltag">{h.icon}</i></span><span><b>{h.name}</b><small className="skillname">{h.skill}</small><small className="heartbar"><i style={{width:`${h.hp/3*100}%`}}/>♥ {h.hp}/3</small></span><i>{h.actions} AP</i></button>)}<div className="objective"><b>OBJECTIVE</b><p>{game.objectives.length?`Secure ${game.objectives.length} supply cache${game.objectives.length>1?"s":""}`:"All survivors reach EVAC"}</p><div className="pips">{[0,1,2].map(i=><i key={i} className={i>=game.objectives.length?"done":""}/>)}</div></div><div className="legend"><span>▣ Search</span><span>🚪 Closed door</span><span>▰ Evac</span><span>▧ Concrete wall</span></div></aside>
    <div className="boardwrap"><div className="board">{Array.from({length:map.w*map.h},(_,i)=>{const x=i%map.w,y=Math.floor(i/map.w),k=`${x},${y}`,zs=game.zombies.filter(z=>z.x===x&&z.y===y),hs=game.heroes.filter(h=>h.x===x&&h.y===y),cellDoors=[...doors.entries()].filter(([,room])=>room===k),isSpawn=spawn.some(s=>s.x===x&&s.y===y);return <button data-active={hs.some(h=>h.id===hero.id)} aria-label={`Zone ${x+1}, ${y+1}`} key={k} disabled={walls.has(k)} onClick={()=>clickCell(x,y)} className={`cell ${buildings.has(k)?"building":"street"} ${walls.has(k)?"wall":""} ${exits.has(k)?"exit":""} ${selected?.x===x&&selected?.y===y?"selected":""}`}><span className="tilelabel">{exits.has(k)?"EVAC":walls.has(k)?"CONCRETE WALL":isSpawn?"SEWER SPAWN":buildings.has(k)?"ROOM":"STREET"}</span>{walls.has(k)&&<span className="concrete">▥</span>}{isSpawn&&<span className="spawn-hole"><i/></span>}{cellDoors.map(([id,room])=><span key={id} className={`door door-${doorSide(id,room)} ${selectedDoor===id?"targeted":""} ${game.openDoors.includes(id)?"opened":""}`}>{game.openDoors.includes(id)?"╱":"▥"}</span>)}<span className="pieces zombie-layer">{zs.map(z=><i key={z.id} className={`zombie-piece zombie-${z.kind}`} data-tooltip={`${z.kind[0].toUpperCase()+z.kind.slice(1)} Zombie`} title={`${z.kind[0].toUpperCase()+z.kind.slice(1)} Zombie`}/>)}{dying.filter(z=>z.x===x&&z.y===y).map(z=><i key={`d${z.id}`} className={`zombie-piece zombie-${z.kind} dying`}/>)}</span>{crates.includes(k)&&!game.searched.includes(k)&&<span className={`crate ${game.objectives.includes(k)?"hot":""}`}>▣</span>}<span className="pieces hero-layer">{hs.map(h=><i key={h.id} className={`survivor-piece survivor-${h.id}`} data-tooltip={h.name} title={h.name}><span className="piecehp">{"♥".repeat(h.hp)}</span></i>)}</span></button>})}</div>{canEvac&&<div className="evacnote">EVAC ROUTE OPEN — GET EVERYONE TO THE GREEN ZONE!</div>}</div>
    <aside className="panel"><div className="turn"><small>CURRENT TURN</small><h2 style={{color:hero.color}}>{hero.name}</h2><div className="health"><b>HEALTH</b><span>{[0,1,2].map(i=><i key={i} className={i<hero.hp?"alive":""}>♥</i>)}</span></div><div className="ap">{[0,1,2].map(i=><i key={i} className={i<hero.actions?"full":""}/>)}</div></div><div className="weapon"><small>ACTIVE HAND</small><span className={`itemart weaponart ${itemClass(weapon.name)}`}/><b>{weapon.name}</b><span>RANGE {weapon.range||"MELEE"} · DMG {weapon.damage}</span></div><button className="inventorybtn" onClick={()=>setInventory(true)}><span className="bagicon itemart item-backpack"/> INVENTORY <span>2 HAND · 3 CARRY</span></button><div className="actions"><div className="action-tip" data-tooltip={!canSearch?searchTip:""}><button disabled={!canSearch} onClick={search}>▣ SEARCH</button></div><div className="action-tip" data-tooltip={!canOpenDoor?doorTip:""}><button disabled={!canOpenDoor} onClick={openDoor}>🚪 OPEN / BREAK DOOR</button></div><div className="action-tip" data-tooltip={!canHeal?healTip:""}><button disabled={!canHeal} onClick={heal}>✚ USE MEDKIT</button></div><button className="end" onClick={endTurn}>END TURN →</button></div><div className="combatlog"><b>RADIO CHATTER</b>{game.log.map((l,i)=><p key={i}>{l}</p>)}</div>{game.mode==="online"&&<div className={`link ${connected?"good":""}`}>● {connected?"PARTNER CONNECTED":"OFFLINE — LOCAL CONTROL"}</div>}</aside>
   </div>
   {briefing&&<div className="missionbrief"><div><small>MISSION {MISSIONS.findIndex(m=>m.id===map.id)+1}</small><h2>{map.title}</h2><p>{map.story}</p><section><b>OBJECTIVES</b><span>{map.objectivesText}</span></section><section><b>SQUAD</b><span>{game.heroes.map(h=>h.name).join(" · ")}</span></section><button className="primary" onClick={()=>setBriefing(false)}>BEGIN MISSION</button></div></div>}
   {inventory&&<div className="modal inventorymodal"><div><button className="close" onClick={()=>{setInventory(false);setPicked(null)}}>×</button><span>LOADOUT</span><h2>{hero.name} · {hero.actions} AP</h2><p>Select two slots to swap. Moving equipment costs 1 action.</p><h3>IN HAND</h3><div className="slots hands">{hero.hands.map((item,i)=><button key={i} className={picked?.area==="hands"&&picked.index===i?"picked":""} onClick={()=>moveItem("hands",i)}>{item?<i className={`itemart ${itemClass(item.name)}`}/>:<i className="emptyart">+</i>}<b>{item?.name||"EMPTY"}</b>{item&&<small>DMG {item.damage} · RNG {item.range||"M"}</small>}</button>)}</div><h3>CARRIED</h3><div className="slots">{hero.bag.map((item,i)=><button key={i} className={picked?.area==="bag"&&picked.index===i?"picked":""} onClick={()=>moveItem("bag",i)}>{item?<i className={`itemart ${itemClass(item.name)}`}/>:<i className="emptyart">+</i>}<b>{item?.name||"EMPTY"}</b>{item&&<small>{item.door?"BREACH TOOL":item.heal?"RESTORE 2 HP":`DMG ${item.damage}`}</small>}</button>)}</div><h3>FIELD MEDIC · SAME ZONE</h3><div className="trade medic-actions">{game.heroes.filter(h=>h.id!==hero.id&&h.x===hero.x&&h.y===hero.y&&h.hp<3).map(h=><button key={h.id} disabled={!hero.hands.some(v=>v?.heal)||hero.actions<1} title={!hero.hands.some(v=>v?.heal)?"Equip a Medkit in your hand":hero.actions<1?"No actions left to use the Medkit":`Restore 2 health to ${h.name}`} onClick={()=>healTeammate(h.id)}>✚ USE MEDKIT ON {h.name} · {h.hp}/3 HP</button>)}{!game.heroes.some(h=>h.id!==hero.id&&h.x===hero.x&&h.y===hero.y&&h.hp<3)&&<small>No injured teammate in this zone.</small>}</div><h3>TRADE IN THIS ZONE</h3><div className="trade">{game.heroes.filter(h=>h.id!==hero.id&&h.x===hero.x&&h.y===hero.y).map(h=><button key={h.id} onClick={()=>{const idx=hero.bag.findIndex(Boolean);if(idx>=0)giveItem(idx,h.id)}}>GIVE FIRST CARRIED ITEM TO {h.name}</button>)}{!game.heroes.some(h=>h.id!==hero.id&&h.x===hero.x&&h.y===hero.y)&&<small>No other survivor here.</small>}</div></div></div>}
   {game.status==="won"&&<div className="victory"><div className="background-fires outcome-fires" aria-hidden><i/><i/><i/></div><div className="defeatcopy"><span>EVACUATED</span><h2>YOU MADE IT OUT ALIVE</h2><p>Survived {game.round} rounds · {game.heroes.reduce((n,h)=>n+h.kills,0)} infected eliminated</p><button className="primary" onClick={()=>start(game.mode)}>PLAY AGAIN</button><button onClick={()=>setScreen("menu")}>MAIN MENU</button></div></div>}
   {game.status==="lost"&&<div className="defeat"><div className="background-fires outcome-fires" aria-hidden><i/><i/><i/></div><div className="defeatcopy"><span>THE HORDE WINS</span><h2>NO ONE MADE IT OUT</h2><p>The city swallowed your entire squad after {game.round} rounds.</p><button className="primary" onClick={()=>{setRoomId("");history.replaceState({},"",location.pathname);setScreen("menu")}}>RETURN TO MAIN MENU</button></div></div>}
   {confirmQuit&&<div className="modal confirm"><div><span>ABANDON MISSION?</span><h2>{isHost?"THIS WILL END THE GAME FOR EVERY PLAYER":"LEAVE THIS SESSION?"}</h2><p>{isHost?"Your team will be returned to the main menu and the invite link will close.":"The other survivors can continue without you."}</p><button className="primary" onClick={terminateGame}>{isHost?"END GAME FOR EVERYONE":"LEAVE GAME"}</button><button onClick={()=>setConfirmQuit(false)}>KEEP PLAYING</button></div></div>}
  </section>}
 </main>
}
